import ImageSource from "../classes/ImageSource";
import Tilemap from "../classes/Tilemap";
import Tileset from "../classes/Tileset";
import map from "../tilemaps/map.json";
import map2 from "../tilemaps/map-2.json";
import map3 from "../tilemaps/map-3.json";
import floors from "../tilesets/floors.json";
import walls from "../tilesets/walls.json";
import furniture from "../tilesets/furniture.json";
import collision from "../tilesets/collision.json";
import obstacles from "../tilesets/obstacles.json";
import AudioSource from "../classes/AudioSource";
import MusicTrack from "../classes/MusicTrack";
import Noise from "../classes/Noise";

const define = (): void => {
  new Tilemap("map", map)
  new Tilemap("map-2", map2)
  new Tilemap("map-3", map3)
  new ImageSource("coots");
  new Tileset("floors", floors);
  new Tileset("walls", walls);
  new Tileset("furniture", furniture);
  new Tileset("collision", collision);
  new Tileset("obstacles", obstacles);
  new ImageSource("tilesets/floors");
  new ImageSource("tilesets/walls");
  new ImageSource("tilesets/furniture");
  new ImageSource("tilesets/collision");
  new ImageSource("tilesets/obstacles");
  new ImageSource("indicator");
  new ImageSource("interact-hud");
  new ImageSource("game-over");
  new ImageSource("victory");
  new ImageSource("scratch");
  new ImageSource("title");
  new ImageSource("pattern");
  new ImageSource("buttons/next");
  new ImageSource("buttons/again");
  new ImageSource("hunger");
  new ImageSource("eating");
  new ImageSource("bed");
  new AudioSource("music/title", 0);
  new AudioSource("music/main", 132000);
  new AudioSource("music/victory", 70500);
  new AudioSource("music/defeat", null);
  new AudioSource("music/level", null);
  new MusicTrack("title", { audioSourceSlug: "music/title" });
  new MusicTrack("main", { audioSourceSlug: "music/main" });
  new MusicTrack("victory", { audioSourceSlug: "music/victory" });
  new MusicTrack("defeat", { audioSourceSlug: "music/defeat" });
  new MusicTrack("level", { audioSourceSlug: "music/level" });
  new AudioSource("noises/scratch", null);
  new AudioSource("noises/meow", null);
  new AudioSource("noises/bounce", null);
  new AudioSource("noises/destroy/electronic", null);
  new AudioSource("noises/destroy/wood", null);
  new AudioSource("noises/destroy/scratch", null);
  new AudioSource("noises/destroy/cloth", null);
  new AudioSource("noises/destroy/container", null);
  new Noise("scratch", { audioSourceSlug: "noises/scratch" });
  new Noise("meow", { audioSourceSlug: "noises/meow" });
  new Noise("bounce", { audioSourceSlug: "noises/bounce" });
  new Noise("destroy/electronic", { audioSourceSlug: "noises/destroy/electronic" });
  new Noise("destroy/wood", { audioSourceSlug: "noises/destroy/wood" });
  new Noise("destroy/scratch", { audioSourceSlug: "noises/destroy/scratch" });
  new Noise("destroy/cloth", { audioSourceSlug: "noises/destroy/cloth" });
  new Noise("destroy/container", { audioSourceSlug: "noises/destroy/container" });
};

export default define;